module.exports = {
  ENDPOINT_ENV_VAR_KEY: 'ENDPOINT',
  CONTRACT_CALL_TIME_OUT_TIME: 3000,
  ETHERSCAN_ENV_VAR_KEY: 'ETHERSCAN_API_KEY',
  HARDHAT_CONFIG_FILE_NAME: 'hardhat.config.js',
  FLATTENED_CONTRACT_FILE_NAME: 'flattened.sol',
}
